import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Image from 'ui/components/atoms/Image'
import Link from 'ui/components/atoms/Link'

import * as Styled from './HomePage.styled'

const HomePage: NextPage = () => (
  <Styled.Container>
    <Head>
      <title>Create Next App</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>

    <Styled.Main>
      <Styled.Title>
        Welcome to{' '}
        <Link
          external
          href="https://nextjs.org"
        >
          Next.js!
        </Link>
      </Styled.Title>

      <Styled.Description>
        Get started by editing{' '}
        <Styled.Code>app/views/HomePage/HomePage.tsx</Styled.Code>
      </Styled.Description>
      <Styled.Footer>
        <Image
          alt="Next.js"
          src="/nextjs.png"
          width={80}
          height={48}
        />
      </Styled.Footer>
    </Styled.Main>
  </Styled.Container>
)

export default HomePage
